language: python

python:
  - "3.6"

before_install:

  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update -q conda


install:

  # We just set up a conda environment with the right Python version. This
  # should not need changing.

  - conda create -q -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install numpy, scipy, h5py

script: 
  
  - cd fort_src/
  - f2py -c --verbose --opt='-O3' -m ThermalCCSD ThermalCCSD.f9# #--f90flags="-fopenmp" -lgomp
  - f2py -c --verbose --opt='-O3' -m ThermalCISD ThermalCISD.f90 #--f90flags="-fopenmp" -lgomp
  - f2py -c --verbose --opt='-O3' -m ExpVals ExpVals.f90 #--f90flags="-fopenmp" -lgomp    
  - cd ../tests
  - pytest --verbose
